name: 'modelagem_eleicoes'
version: '1.0.0'

profile: 'modelagem_eleicoes'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  modelagem_eleicoes:
    staging:
      schema: staging
      +materialized: view

    intermediate:
      schema: intermediate
      +materialized: view

    marts:
      schema: marts
      +materialized: table

seeds:
  modelagem_eleicoes:
    +schema: raw
    +quote_columns: false
    +materialized: seed